# Generated by Django 5.0.6 on 2024-07-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_taggs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='taggs',
            new_name='tags',
        ),
    ]
